---
- name: Create user key entry ssh
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
  username: user_nginx
  userpass: qwerty
  super_group: sudo
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: {{ username }}
        comment: new user1
        state: present
        shell: /bin/bash
        password: "{ userpass | password_hash('sha512')}"
        update_password: on_create
        groups: "{{ super_group }}"
        append: yes

    - name: Deploy SSH public key
      ansible.builtin.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
        #key: "{{ lookup('file', '/home/{{ username }}/ssh.id_rsa.pub') }}"
