---
- name: Install dnsmasq
  hosts: loalhost
  become: yes
  tasks:
    - name: Stop and disable systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enable: no

    - name: Config file resolv.conf
      ansible.builtin.template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf

    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: latest
        update_cache: yes

    - name: Install dnsmasq
      ansible.builtin.apt:
        name: dnsmasq
        state: present
        update_cache: true

    - name: starts and allows the Dnsmasq service to start on system boot
      shell: systemctl status dnsmasq

    - name: Create dnsmasq.conf
      ansible.builtin.template:
        src: dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf

    - name: Allow all access to tcp port 53
      community.general.ufw:
        rule: allow
        port: "53"
        proto: udp

  handlers: 
  - name: Restart dnsmasq
    ansible.builtin.service:
      name: dnsmasq
      state: restarted
      enable: yes

